### ISSUE TITLE
Error -10810 on OS X

### ISSUE THREAD

**Issue by larsroe** [beryx/fxgl-sliding-puzzle#1]
Hello. I ran the following on OS X:

$ git clone https://github.com/beryx/fxgl-sliding-puzzle
$ ./gradlew jpackage

Then installed by dragging the icon to Applications.

But when I double-clicked the application, nothing happened.

My troubleshooting:
By running "open /Applications/sliding\ puzzle.app" in Terminal, I get the error:
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/sliding puzzle.app.

In console.log, I see the following error:
com.apple.xpc.launchd[1] (org.beryx.fxgl.puzzle.17116[18730]): Service exited with abnormal code: 255
 
Advice welcome. Thank you.

**Comment by larsroe** [comment]
This works fine for me:
$ ./gradlew run

It also "works" if I comment out the launch() part of main and run the bundled version, but then again nothing really happens. I only verified it runs when I add some dummy logging before the now commented-out launch().

My guess is that there's some kind of permissions error, but I haven't worked with FXGL before and unsure how to debug.

**Comment by siordache** [comment]
Yes, it looks like a permission issue. I don't have a Mac, so I tested the application only on Linux and Windows.
Tomorrow I will install Mac OS in a VirtualBox and I will try to reproduce this issue.

I just found this bug:  https://bugs.openjdk.java.net/browse/JDK-8248501, which seems to affect the jpackage tool found in JDK 15 and 16. Which JDK did you use?

**Comment by siordache** [comment]
I installed macOS Catalina 10.15.7 on a VirtualBox running on Ubuntu and I encountered two problems when trying to execute the application.

The first one occurred when executing `./gradlew run` or when starting the runtime image produced by jlink: `./build/image/bin /sliding\ puzzle`.The application showed only an empty window due to [this OpenJFX bug](https://bugs.openjdk.java.net/browse/JDK-8235627), which has been fixed in recent JavaFX versions. To get rid of this problem I configured the build to [use JavaFX version 15](https://github.com/beryx/fxgl-sliding-puzzle/blob/c26501d1e9fcdc3ab9d575165f1b91f5b13f8597/build.gradle#L20).

The second problem was the failure to start the packaged application: `LSOpenURLsWithRole() failed with error -10810 for the file /Applications/sliding puzzle.app`. As you correctly guessed, this was a permission issue.  FXGL tries to create a directory named `logs` in the current working directory, where log files will be written. When starting the application with `open /Applications/sliding\ puzzle.app` or by double-clicking on its icon, the current working directory is `/`, so FXGL fails to initialize, because it has no permission to create the log files. To solve this problem, I [set the system property `user.dir` to `/tmp`](https://github.com/beryx/fxgl-sliding-puzzle/blob/c26501d1e9fcdc3ab9d575165f1b91f5b13f8597/build.gradle#L57).

Please execute `git pull` to get the latest version of the source code, which contains the above mentioned changes. Then check if `./gradlew run` works as expected and if `./gradlew jpackage` produces a valid application package.

On my VirtualBox it works now with both JDK 15 and JDK 14. It also works with JDK 11 if you set the path to the home of a JDK 14 or 15 in the BADASS_JLINK_JAVA_HOME environment variable.

**Comment by larsroe** [comment]
Awesome! I just verified that this change works for me now. Thanks so much for the quick turnaround.
